name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./BuildMap/Dockerfile --tag build_map:$(date +%s)
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Docker Login, Build, Tag & Push Action
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          # Username to connect to Docker registry
          username: ${{ secret.DOCKER_HUB_NAME }}
          # Password to connect to Docker registry
          password:  ${{ secret.DOCKER_HUB_PASSWORD }}
          # Docker build context
          context: default
          # Docker build file
          file: ./BuildMap/Dockerfile
          # Docker repository owner
          repoOwner: ${{ secret.DOCKER_HUB_NAME }}
          # Docker repository
          repository: ${{ secret.BUILD_MAP_REPOSITORY_NAME }}
          # Docker image tag
          tag: latest

